# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160811_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
