# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_track_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='date_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
