# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160811_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
