# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playlist_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='owner_id',
        ),
    ]
