# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160821_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlist_id',
        ),
    ]
