# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_track_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playlist_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Playlist'),
            preserve_default=False,
        ),
    ]
