# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160821_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='image_url',
        ),
    ]
