# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_track_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url_checksum',
            field=models.CharField(default='123', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
