# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='api.Track'),
        ),
    ]
