# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160823_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='playlist_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Playlist'),
            preserve_default=False,
        ),
    ]
