# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160823_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url_checksum',
            field=models.CharField(max_length=32),
        ),
    ]
