# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160824_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlist_id',
        ),
    ]
